name: ESlint
on: [push]

jobs:
    eslint:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node 14.x Environment
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"

            - name: Install dependencies
              working-directory: ./
              run: npm ci

            - name: Run lint
              working-directory: ./
              run: npm run lint
