name: Lighthouse
on: [push]

jobs:
    ci:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node 14.x Environment
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"

            - name: Install dependencies
              working-directory: ./
              run: npm ci && npm install -g @lhci/cli

            - name: Build
              working-directory: ./
              run: npm run build

            - name: Run lighthouse
              working-directory: ./
              run: lhci autorun
